checks:
    php:
        excluded_dependencies:
            - atoum/atoum
            - atoum/config-extension
            
tools:
    php_cs_fixer:
        config: { level: psr2 }

build:
    tests:
        override:
            - 
                command: 'vendor/bin/atoum'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
             
