---
sudo: false

language: php
matrix:
    include:
        - php: 7.3
        - php: 7.2

install:
    - composer install

script:
    - vendor/bin/phpstan analyse -c phpstan.neon src/
    - vendor/bin/atoum
