---
language: php
matrix:
    include:
        - php: 8.0
          env: 'XDEBUG_MODE=coverage SCENARIO=symfony5'
        - php: 7.4
          env: 'XDEBUG_MODE=coverage SCENARIO=symfony5'
        - php: 7.4
          env: 'XDEBUG_MODE=coverage SCENARIO=symfony4'
        - php: 7.3
          env: 'XDEBUG_MODE=coverage SCENARIO=symfony4'
        - php: 7.3
          env: 'XDEBUG_MODE=coverage SCENARIO=symfony3'
        - php: 7.3
          env: 'XDEBUG_MODE=coverage SCENARIO=symfony2 DEPENDENCIES=lowest'
        - php: 7.2
          env: 'XDEBUG_MODE=coverage SCENARIO=symfony4 DEPENDENCIES=lowest'

install:
  - '.scenarios.lock/install "${SCENARIO}" "${DEPENDENCIES}"'

script:
    - vendor/bin/phpstan analyse -c phpstan.neon src/
    - vendor/bin/atoum
